id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
hardware_id: imu0
sensor_type: IMU
sigmas:
  gyro_noise_density: 1.22e-3 #0.000244*5
  gyro_bias_random_walk_noise_density: 3.5e-6 #7e-7*5 
  acc_noise_density: 7.35e-3 #0.00147*5
  acc_bias_random_walk_noise_density: 4e-4 #8e-5*5
saturation_accel_max_mps2: 150.0
saturation_gyro_max_radps: 7.5
gravity_magnitude_mps2: 9.81
